# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True)),
                ('importe', models.DecimalField(decimal_places=2, default='30.00', max_digits=5)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsocio', models.CharField(max_length=10)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mail', models.EmailField(max_length=75)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha solicitud')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('is_junta', models.BooleanField(default=False)),
                ('is_fundador', models.BooleanField(default=False)),
                ('is_activo', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.Socio'),
        ),
    ]
