# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
