# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20161016_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha solicitud', null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nsocio',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
