# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='comentario',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
