# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_socio_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='iban',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
